apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: my-sinatra-app
    app.kubernetes.io/part-of: my-sinatra-app
  name: my-sinatra-app
spec:
  ports:
  - name: web
    port: 8080
    protocol: TCP
    targetPort: web
  selector:
    app.kubernetes.io/name: my-sinatra-app